name: planandbill
description: "Art Therapy Management App for appointments and billing"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_app_check: ^0.2.1+6
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.6

  # State Management
  provider: ^6.1.1

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # Date/Time
  intl: ^0.18.1

  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.12.0

  # Utilities
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
